#ifndef __SDCC_INTELLISENSE__
#define __SDCC_INTELLISENSE__

/*
    DO NOT EDIT!

    VS Code shows error bc SDCC spesific intellisense
    This file created just for get rid of unnecessary

    "SDCC" is known by the compiler
*/

#ifndef SDCC
    
    #define __bit
    #define __code
    #define __xdata
    #define __data
    #define __pdata
    #define __at(x)
    #define __sbit
    #define __sfr
    #define __asm
    #define __endasm
    #define __interrupt
    #define __using
    #define bool uint8_t


#define P2SR   
#define PIPS0  
#define PIPS1  
#define PIPS2  
#define PIPS3  
#define PIPS4  
#define PIPS5  
#define PIPS6  
#define VRFCON 
#define VRFTRIM
#define ACMPCR2
#define LIRCTRIM
#define XLTCON  
#define CWKL    
#define P0DW    
#define P1DW    
#define P2DW    
#define P3DW    
#define P4DW    
#define P5DW    
#define P0UP    
#define P1UP    
#define P2UP    
#define P3UP    
#define P4UP    
#define P5UP    
#define DMA1TSR
#define MTM1DAL
#define SPI0CR0
#define SPI0SR 
#define SPI0DR 
#define DMA0BAH
#define EIPH0  
#define S1CON  
#define SPI1CR0
#define SPI1CR1
#define SPI1SR 
#define SPI1DR 
#define DMA1BAH
#define ADCBAH  
#define ADCSN   
#define ADCCN   
#define ADCSR   
#define I2C1CON 
#define DMA0TSR 
#define MTM0DAL 
#define DMA1CR0 
#define DMA1MAL 
#define DMA1CNT 
#define DMA1CCNT
#define EIP0    
#define PWM0CON0 
#define ACMPCR0  
#define ACMPCR1  
#define ACMPSR   
#define ACMPVREF 
#define SC0CR0   
#define SC0CR1   
#define P4       
#define SC0DR    
#define SC0EGT   
#define SC0ETURD0
#define SC0ETURD1
#define SC0IE    
#define SC0IS    
#define SC0TSR   
#define ADCBAL
#define SADEN1   
#define SADDR1   
#define I2C0DAT  
#define I2C0STAT 
#define I2C0CLK  
#define I2C0TOC  
#define I2C0CON  
#define I2C0ADDR0
#define P5       
#define I2C1ADDR0
#define I2C1DAT  
#define I2C1STAT 
#define I2C1CLK  
#define I2C1TOC  
#define EIP2 
#define EIPH2
#define AUXR0
#define SBUF1
#define EIE0 
#define RSR  
#define DMA0CR0 
#define DMA0MAL 
#define DMA0CNT 
#define DMA0CCNT
#define RWKL
#define P0
#define SP
#define DPL
#define DPH
#define RCTRIM0
#define RCTRIM1
#define RWK
#define PCON
#define TCON
#define TMOD
#define TL0
#define TL1
#define TH0
#define TH1
#define CKCON
#define WKCON
#define P1
#define SFRS
#define CAPCON0
#define CAPCON1
#define CAPCON2
#define CKDIV
#define CKSWT
#define CKEN
#define SCON
#define SBUF
#define SBUF_1
#define EIE
#define EIE1
#define CHPCON
#define P2
#define AUXR1
#define BODCON0
#define IAPTRG
#define IAPUEN
#define IAPAL
#define IAPAH
#define IE
#define SADDR
#define WDCON
#define BODCON1
#define P3M1
#define P3S
#define P3M2
#define P3SR
#define IAPFD
#define IAPCN
#define P3
#define P0M1
#define P0S
#define P0M2
#define P0SR
#define P1M1
#define P1S
#define P1M2
#define P1SR
#define P2S;
#define IPH
#define PWMINTC
#define IP
#define SADEN
#define SADEN_1
#define SADDR_1
#define I2DAT
#define I2STAT
#define I2CLK
#define I2TOC
#define I2CON
#define I2ADDR
#define ADCRL
#define ADCRH
#define T3CON
#define PWM4H
#define RL3
#define PWM5H
#define RH3
#define PIOCON1
#define TA
#define T2CON
#define T2MOD
#define RCMP2L
#define RCMP2H
#define TL2;
#define PWM4L
#define TH2
#define PWM5L
#define ADCMPL
#define ADCMPH
#define PSW
#define PWMPH
#define PWM0H
#define PWM1H
#define PWM2H
#define PWM3H
#define PNP
#define FBD
#define PWMCON0
#define PWMPL
#define PWM0L
#define PWM1L
#define PWM2L
#define PWM3L
#define PIOCON0
#define PWMCON1
#define ACC
#define ADCCON1
#define ADCCON2
#define ADCDLY
#define C0L
#define C0H
#define C1L
#define C1H
#define ADCCON0
#define PICON
#define PINEN
#define PIPEN
#define PIF
#define C2L
#define C2H
#define EIP
#define B
#define CAPCON3
#define CAPCON4
#define SPCR
#define SPCR2
#define SPSR
#define SPDR
#define AINDIDS
#define EIPH
#define SCON_1
#define PDTEN
#define PDTCNT
#define PMEN
#define PMD
#define EIP1
#define EIPH1
#define SM0_1
#define FE_1
#define SM1_1
#define SM2_1
#define REN_1
#define TB8_1
#define RB8_1
#define TI_1
#define RI_1
#define ADCF
#define ADCS
#define ETGSEL1
#define ETGSEL0
#define ADCHS3
#define ADCHS2
#define ADCHS1
#define ADCHS0
#define PWMRUN
#define LOAD
#define PWMF
#define CLRPWM
#define CY
#define AC
#define F0
#define RS1
#define RS0
#define OV
#define P
#define TF2
#define TR2
#define CM_RL2
#define I2CEN
#define STA
#define STO
#define SI
#define AA
#define I2CPX
#define PADC
#define PBOD
#define PS
#define PT1
#define PX1
#define PT0
#define PX0
#define P30
#define EA
#define EADC
#define EBOD
#define ES
#define ET1
#define EX1
#define ET0
#define EX0
#define P20
#define SM0
#define FE
#define SM1
#define SM2
#define REN
#define TB8
#define RB8
#define TI
#define RI
#define P17
#define P16
#define TXD_1
#define P15
#define P14
#define SDA
#define P13
#define SCL
#define P12
#define P11
#define P10
#define TF1
#define TR1
#define TF0
#define TR0
#define IE1
#define IT1
#define IE0
#define IT0
#define P07
#define RXD
#define P06
#define TXD
#define P05
#define P04
#define STADC
#define P03
#define P02
#define RXD_1
#define P01
#define MISO
#define P00
#define MOSI
#define LDOTRIM    
#define SPI0CR1    
#define PWM0DTEN   
#define PWM0DTCNT  
#define PWM0MEN    
#define PWM0MD     
#define LVRFLTEN   
#define LVRDIS     
#define P6M1       
#define P6M2       
#define PWM1PH     
#define PWM1C0H    
#define PWM1C1H    
#define PWM1MD     
#define PWM1MEN    
#define P6SR       
#define P6DW       
#define P6MF10     
#define P6MF32     
#define P6MF54     
#define P6MF76     
#define P6S        
#define P6UP       
#define PWM1PL     
#define PWM1C0L    
#define PWM1C1L    
#define PWM1CON0   
#define PWM1CON1   
#define PWM1INTC   
#define I2C0ADDR1  
#define I2C0ADDR2  
#define I2C0ADDR3  
#define I2C1ADDR1  
#define I2C1ADDR2  
#define I2C1ADDR3  
#define P6         
#define DMA3TSR    
#define DMA3BAH    
#define DMA3CR0    
#define DMA3MAL    
#define DMA3CNT    
#define DMA3CCNT   
#define MTM3DAL    
#define DMA2TSR    
#define DMA2BAH    
#define DMA2CR0    
#define DMA2MAL    
#define DMA2CNT    
#define DMA2CCNT   
#define MTM2DAL    
#define PWM2PH     
#define PWM2C0H    
#define PWM2C1H    
#define PWM2MD     
#define PWM2MEN    
#define CWKH       
#define RWKH       
#define PWM2PL     
#define PWM2C0L    
#define PWM2C1L    
#define PWM2CON0   
#define PWM2CON1   
#define PWM2INTC   
#define PWM3PH     
#define PWM3C0H    
#define PWM3C1H    
#define PWM3MD     
#define PWM3MEN    
#define AINDIDS1   
#define I2C0ADDRM  
#define PWM3PL     
#define PWM3C0L    
#define PWM3C1L    
#define PWM3CON0   
#define PWM3CON1   
#define PWM3INTC  
#define I2C1ADDRM  
#define SC1DR      
#define SC1EGT     
#define SC1ETURD0  
#define SC1ETURD1  
#define SC1IE      
#define SC1IS      
#define SC1TSR     
#define P5MF32     
#define P5MF54     
#define P5MF76     
#define BRCTRIM    
#define ADCCAL     
#define SC1CR0     
#define SC1CR1     
#define P3MF54     
#define P3MF76     
#define P4MF10     
#define P4MF32     
#define P4MF54     
#define P4MF76     
#define P5MF10     
#define P1MF76     
#define P2MF10     
#define P2MF32     
#define P2MF54     
#define P2MF76     
#define P3MF10     
#define P3MF32     
#define P0MF10     
#define P0MF32     
#define P0MF54     
#define P0MF76     
#define P1MF10     
#define P1MF32     
#define P1MF54     
#define DMA0CR1    
#define DMA1CR1    
#define DMA2CR1    
#define DMA3CR1    
#define DMA0CRC    
#define DMA1CRC    
#define DMA2CRC    
#define DMA3CRC    
#define WDCONH     
#define DMA0SEED   
#define DMA1SEED   
#define DMA2SEED   
#define DMA3SEED   
#define RTCINIT    
#define RTCRWEN    
#define RTCCLKSEL  
#define RTCFREQADJ0
#define RTCFREQADJ1
#define RTCINTEN   
#define RTCINTSTS  
#define RTCTIMESEC 
#define RTCTIMEMIN 
#define RTCTIMEHR  
#define RTCCALDAY  
#define RTCCALMON  
#define RTCCALYEAR 
#define RTCTALMSEC 
#define RTCTALMMIN 
#define RTCTALMHR  
#define RTCTALMHZ  
#define RTCCALMDAY 
#define RTCCALMMON 
#define RTCCALMYEAR
#define RTCCLKFMT  
#define RTCWEEKDAY 
#define RTCLEAPYEAR
#define RTCTICK    
#define RTCTAMSK   
#define RTCCAMSK   
#define PWM0FBS    
#define AUXR3      
#define LCDCPALCT1 
#define LCDCPCT1   
#define LCDCPUMP   
#define LCDCON1    
#define LCDCPALCT0 
#define LCDCPCT0   
#define LCDCON0    
#define LCDCLK     
#define LCDPTR     
#define LCDDAT     
#define LCDPWR     
#define LCDBL      
#define LCDMODE    
#define P5SR 
#define PIPS7
#define P2M1    
#define P2M2    
#define PWM0INTC
#define P4M1    
#define P4M2    
#define P4S     
#define P4SR    
#define P5M1    
#define P5M2    
#define P5S     
#define PWM0C4H
#define PWM0C5H
#define PORDIS 
#define PWM0C4L 
#define PWM0C5L 
#define AINDIDS0
#define PWM0PH  
#define PWM0C0H 
#define PWM0C1H 
#define PWM0C2H 
#define PWM0C3H 
#define PWM0NP  
#define PWM0FBD 
#define PWM0PL  
#define PWM0C0L 
#define PWM0C1L 
#define PWM0C2L 
#define PWM0C3L 
#define PWM0CON1
#define AIN0
#define AIN1
#define AIN2
#define AIN3
#define AIN4
#define AIN5
#define AIN6
#define AIN7
#define P27
#define P26
#define P25
#define P24
#define P23
#define P22
#define P21
#define P37
#define P36
#define P35
#define P34
#define P33
#define P32
#define P31
#define I2CEN0
#define STA0  
#define STO0  
#define SI0   
#define AA0   
#define I2C0PX
#define I2CEN1
#define STA1
#define STO1
#define SI1 
#define AA1 
#define I2CPX1
#define P47 
#define P46 
#define P45 
#define P44 
#define P43 
#define P42 
#define P41
#define P40

#endif
#endif